services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: "db_name"
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - database_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  custom_nginx:
    # собираем кастомный nginx из Dockerfile
    build: .
    container_name: custom_nginx
    ports:
      - "80:80"
    depends_on:
      # запускаем только после БД
      - database

volumes:
  database_data: